path_proxy_list: '/../../../source/'
filename_proxy_list: 'proxylist.txt'
path_results: '/../../../logs/'
filename_results: 'result'
checkpoint_url: 'http://httpbin.org/get'
show_result_in_console: true