proxy_checker:
  curl:
    checkpoint_url: 'http://httpbin.org/get'
    thread: 5
  console:
    show: true
  log_results:
    filename: 'result'
    path: '/../../../logs/'
  proxy-list:
    path: '/../../../source/'
    filename: 'proxylist.txt'